
[UpstreamProxy]
  Type = "none"

[Logging]
  Disable = false
  Level = "DEBUG"
  File = "/tmp/meson/ping.log"

[Katzenmint]
    ChainID = "test-chain-QvpdAC"
    PrimaryAddress = "tcp://127.0.0.1:26657"
    WitnessesAddresses = [ "127.0.0.1:26657" ]
    DatabaseName = "ping"
    DatabaseDir = "/tmp/meson/ping"
    RPCAddress = "tcp://127.0.0.1:26657"

    [Katzenmint.TrustOptions]
      Period = 600000000000
      Height = 13
      Hash = [54, 57, 47, 184, 187, 218, 235, 146, 116, 42, 17, 26, 39, 62, 241, 55, 25, 108, 10, 156, 59, 217, 7, 96, 76, 102, 248, 214, 37, 129, 9, 106]

[Debug]
  PollingInterval = 10
  SessionDialTimeout = 1200000
  